config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :big_foot_reports, only: [:index, :show, :new, :create]

  get '/about',                   to: 'about#index'
  get 'auth/:provider/callback',  to: 'sessions#create'
  get 'logout',                   to: 'sessions#destroy'
  get '/squatch_map',             to: 'squatch_map#index'
  get '/search',                  to: 'search#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/big_foot_report.rb
class BigFootReport < ApplicationRecord
  # validates :report_number, presence: true
  def self.state_count(state_name)
    where(state: state_name).count
  end

  def self.order_by_report_number
    order(:report_number)
  end

  def find_date
    "#{date} #{month} #{year}"
  end

  def self.search_by_state(state)
    where(state: state)
  end

  def self.search_by_report_number(report_number)
    where(report_number: report_number)
  end

  def self.search_by_year(year)
    where(year: year)
  end

  def self.search_by_season(season)
    where(season: season)
  end

  def self.search_by_report_class(report_class)
    where(report_class: report_class)
  end
end

app/models/user.rb
class User < ApplicationRecord

  def self.update_or_create(auth)
    user = User.find_by(uid: auth[:uid]) || User.new
    user.attributes = {
      provider: auth[:provider],
      uid: auth[:uid],
      email: auth[:info][:email],
      first_name: auth[:info][:first_name],
      last_name: auth[:info][:last_name],
      token: auth[:credentials][:token],
      refresh_token: auth[:credentials][:refresh_token],
      oauth_expires_at: auth[:credentials][:expires_at]
    }
    user.save!
    user
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:id]) if session[:id]
  end
end

app/controllers/big_foot_reports_controller.rb
class BigFootReportsController < ApplicationController

  def index
    if current_user
      @big_foot_reports = BigFootReport.order_by_report_number.paginate(:page => params[:page], :per_page => 30)
    else
      redirect_to root_path
      flash[:notice] = "Please create an account or login first"
    end
  end

  def show
    if current_user
      @big_foot_report = BigFootReport.find(params[:id])
    else
      redirect_to root_path
      flash[:notice] = "Please create an account or login first"
    end
  end

  def new
    if current_user
      @big_foot_report = BigFootReport.new
    else
      redirect_to root_path
      flash[:notice] = "Please create an account or login first"
    end
  end

  def create
    @big_foot_report = BigFootReport.new(big_foot_report_params)
    @big_foot_report.save
    @big_foot_report.update!(report_number: @big_foot_report.id + 58238)
    @big_foot_report.update!(id: @big_foot_report.report_number)
    redirect_to big_foot_report_path(@big_foot_report.id)
    flash[:notice] = "Your Samsquantch Report has been saved!"
  end

  private

  def big_foot_report_params
    params.require(:big_foot_report).permit(:report_number, :report_class, :state, :season, :date, :month, :year, :environment, :location_details, :observed, :also_noticed, :other_witnesses, :other_stories, :time_and_conditions, :county, :nearest_town, :nearest_road, :a_g_references)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if current_user
      @search_by_state = BigFootReport.search_by_state(params[:search]).paginate(:page => params[:page], :per_page => 30)
      @search_by_report_number = BigFootReport.search_by_report_number(params[:search])
      @search_by_year = BigFootReport.search_by_year(params[:search]).paginate(:page => params[:page], :per_page => 30)
      @search_by_season = BigFootReport.search_by_season(params[:search]).paginate(:page => params[:page], :per_page => 30)
      @search_by_report_class = BigFootReport.search_by_report_class(params[:search]).paginate(:page => params[:page], :per_page => 30)
    else
      redirect_to root_path
      flash[:notice] = "Please create an account or login first"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.update_or_create(request.env["omniauth.auth"])
    session[:id] = user.id
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/squatch_map_controller.rb
class SquatchMapController < ApplicationController
  def index
    @big_foot_reports = BigFootReport.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h2>About Squatch Watch</h2>

<h3>Report Classification System</h3>
<h4>Taken from the official BRFO (Bigfoot Field Researchers Organization) Website</h4>
<h4>Class A</h4>
<p>Class A reports involve clear sightings in circumstances where misinterpretation or misidentification of other animals can be ruled out with greater confidence. For example, there are several footprint cases that are very well documented. These are considered Class A reports, because misidentification of common animals can be confidently ruled out, thus the potential for misinterpretation is very low.</p>
<h4>Class B</h4>
<p>Incidents where a possible sasquatch was observed at a great distance or in poor lighting conditions and incidents in any other circumstance that did not afford a clear view of the subject are considered Class B reports.</p>
<p>For example, credible reports where nothing was seen but distinct and characteristic sounds of sasquatches were heard are always considered Class B reports and never Class A, even in the most compelling "sound-only" cases. This is because the lack of a visual element raises a much greater potential for a misidentification of the sounds.</p>
<p>Class B reports are not considered less credible or less important than Class A reports--both types are deemed credible enough by the BFRO to show to the public. For example, one of the best documented reports ever received by the BFRO is a Class B report from Trinity County California. It involved a very credible witness who backpacked into a remote area that has a history of sasquatch-related incidents. He described various occurrences around his camp at night that are strongly suspected to be sasquatch-related. The report is still considered Class B though because there was no clear visual observation to confirm what was heard outside the tent.</p>
<p>Almost all reports included in the database are first-hand reports. Occassionally a second-hand report is considered reliable enough to add to the database, but those reports are never Class A, because of the higher potential for inaccuracy when the story does not come straight from the eyewitness.</p>
<h4>Class C</h4>
<p>Most second-hand reports, and any third-hand reports, or stories with an untraceable sources, are considered Class C, because of the high potential for inaccuracy. Those reports are kept in BFRO archives but are very rarely listed publicly in this database. The exceptions are for published, or locally documented incidents from before 1948 (before the word "Bigfoot" entered the American vocabulary), and sightings mentioned in non-tabloid newspapers or magazines.</p>

app/views/big_foot_reports/index.html.erb
<h2>Squatch Reports</h2>

<ul>
  <% @big_foot_reports.each do |report| %>
  <li>
    Report Number: <%= link_to "#{report.report_number} #{report.report_class}", big_foot_report_path(report.id) %><br>
  </li>
  <% end %>
</ul>

<%= will_paginate @big_foot_reports %>

app/views/big_foot_reports/new.html.erb
<h2>I Found A Dang Samsquantch!</h2>
<h4>For more information about report classes visit the about page.</h4>
<%= form_for @big_foot_report do |f| %>
  <%= f.label :report_class, "Class the report falls into:" %>
  <%= f.select :report_class, ['Class A', 'Class B', 'Class C']%><br><br>
  <%= f.label :state, "State:" %>
  <%= f.select :state, ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Flordia', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'] %><br><br>
  <%= f.label :season, "Season:" %>
  <%= f.select :season, %w[Spring Summer Fall Winter] %><br><br>
  <%= f.label "Day:" %>
  <%= f.select :date, (1..31).to_a.map(&:to_s) %>
  <%= f.label :month, "Month:" %>
  <%= f.select :month, %w[January February March April May June July August September October November December] %>
  <%= f.label :year, "Year:" %>
  <%= f.select :year, (1918..2018).to_a.map(&:to_s) %><br>
  <p>Please describe the environment where the incident occurred. (E.g., pine forest, swamp, etc. Be sure to note any nearby landmarks or structures. (E.g. creek bottom, mountain ridge, bridges, etc.)</p>
  <%= f.text_area :environment %><br>
  <p>Please provide any other information about the location, including directions to it. NOTE: at your request, this information will not be posted online if it might cause any sort of problems.</p>
  <%= f.text_area :location_details %><br>
  <p>Please tell your whole story here. If you had a visual incident, take extra time to be as descriptive as you can be about the appearance and behavior observed.</p>
  <%= f.text_area :observed %><br>
  <p>If anything else unusual was observed, found, or heard at the location before, during, or after the incident, please note it here.</p>
  <%= f.text_area :also_noticed %><br>
  <p>How many witnesses were involved? What were the witness(es) doing just prior to the incident?</p>
  <%= f.text_field :other_witnesses %><br>
  <p>What time of day or night did the incident occur? Also describe the lighting conditions and weather conditions at the time of the incident.</p>
  <%= f.text_field :time_and_conditions %><br>
  <p>In which county did the incident occur?</p>
  <%= f.text_field :county %><br>
  <p>What was the nearest city or town?</p>
  <%= f.text_field :nearest_town %><br>
  <p>What was the nearest road or highway?</p>
  <%= f.text_field :nearest_road %><br>
  <p>Have you heard of any other incidents like this in the same area? If so, please give any details here.</p>
  <%= f.text_area :other_stories %><br><br>
  <%= f.submit "Submit", method: :create %>
<% end %>

app/views/big_foot_reports/show.html.erb
<h2>Squatch Report: <%= @big_foot_report.report_number %></h2>
<h3>
  <ul>
    <li>Report Class: <%= @big_foot_report.report_class %></li>
    <li>State: <%= @big_foot_report.state %></li>
    <li>Season: <%= @big_foot_report.season %></li>
    <li>Date: <%= @big_foot_report.find_date %></li>
    <li>Environment: <%= @big_foot_report.environment %></li>
    <li>Location Details: <%= @big_foot_report.location_details %></li><br>
    <li>Observed: <%= @big_foot_report.observed %></li><br>
    <li>Also Noticed: <%= @big_foot_report.also_noticed %></li><br>
    <li>Other Witnesses: <%= @big_foot_report.other_witnesses %></li><br>
    <li>Other Stories: <%= @big_foot_report.other_stories %></li><br>
    <li>Time and Conditions: <%= @big_foot_report.time_and_conditions %></li>
    <li>County: <%= @big_foot_report.county %></li>
    <li>Nearest Town: <%= @big_foot_report.nearest_town %></li>
    <li>Nearest Road: <%= @big_foot_report.nearest_road %></li><br>
    <li>AG References: <%= @big_foot_report.a_g_references %></li>
  </ul>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Squatch Watch</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="topnav" id="myTopnav">
      <a class="active" href="/">Squatch Watch</a>
      <%= link_to "Squatch Map", squatch_map_path %>
      <%= link_to "Squatch Reports", big_foot_reports_path %>
      <%= link_to "I Found A Dang Samsquantch!", new_big_foot_report_path %>
      <%= link_to "About", about_path %>
      <% if current_user  %>
        <%= link_to "Logout", logout_path %>
      <% else %>
        <%= link_to "Login with Google", "auth/google" %>
      <% end %>
      <div class="search-container">
        <form action="/search">
          <input type="text" placeholder="Search.." name="search">
          <button type="submit"><i class="fa fa-search"></i></button>
        </form>
      </div>
    </div> 
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<h2>Search Results for <%= params[:search] %></h2>
<ul>
  <% @search_by_state.order_by_report_number.each do |report| %>
    <li>
      Report Number: <%= link_to "#{report.report_number} #{report.report_class}", big_foot_report_path(report.id) %><br>
    </li>
  <% end %>
</ul>
<%= will_paginate @search_by_state %>

<ul>
  <% @search_by_report_number.order_by_report_number.each do |report| %>
    <li>
      Report Number: <%= link_to "#{report.report_number} #{report.report_class}", big_foot_report_path(report.id) %><br>
    </li>
  <% end %>
</ul>

<ul>
  <% @search_by_year.order_by_report_number.each do |report| %>
    <li>
      Report Number: <%= link_to "#{report.report_number} #{report.report_class}", big_foot_report_path(report.id) %><br>
    </li>
  <% end %>
</ul>
<%= will_paginate @search_by_year %>

<ul>
  <% @search_by_season.order_by_report_number.each do |report| %>
    <li>
      Report Number: <%= link_to "#{report.report_number} #{report.report_class}", big_foot_report_path(report.id) %><br>
    </li>
  <% end %>
</ul>
<%= will_paginate @search_by_season %>

<ul>
  <% @search_by_report_class.order_by_report_number.each do |report| %>
    <li>
      Report Number: <%= link_to "#{report.report_number} #{report.report_class}", big_foot_report_path(report.id) %><br>
    </li>
  <% end %>
</ul>
<%= will_paginate @search_by_report_class %>

app/views/squatch_map/index.html.erb
<h2>Squatch Report Map</h2>
<iframe src="https://www.google.com/maps/d/u/0/embed?mid=17R5-mNOE_P8wsE0qpYBPag6P5Rqarkiw" width="800" height="600"></iframe>

<h2>Squatch Report Heat Map</h2>
<!-- Styles -->
<style>
#chartdiv {
  width: 100%;
  height: 500px;
}
</style>

<!-- Resources -->
<script src="https://www.amcharts.com/lib/3/ammap.js"></script>
<script src="https://www.amcharts.com/lib/3/maps/js/usaLow.js"></script>
<script src="https://www.amcharts.com/lib/3/plugins/export/export.min.js"></script>
<link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script>

<!-- Chart code -->
<script>
var map = AmCharts.makeChart( "chartdiv", {
  "type": "map",
  "theme": "none",
  "colorSteps": 10,

  "dataProvider": {
    "map": "usaLow",
    "areas": [ {
      "id": "US-AL",
      "value": <%= @big_foot_reports.state_count("Alabama") %>
    }, {
      "id": "US-AK",
      "value": <%= @big_foot_reports.state_count("Alaska") %>
    }, {
      "id": "US-AZ",
      "value": <%= @big_foot_reports.state_count("Arizona") %>
    }, {
      "id": "US-AR",
      "value": <%= @big_foot_reports.state_count("Arkansas") %>
    }, {
      "id": "US-CA",
      "value": <%= @big_foot_reports.state_count("California") %>
    }, {
      "id": "US-CO",
      "value": <%= @big_foot_reports.state_count("Colorado") %>
    }, {
      "id": "US-CT",
      "value": <%= @big_foot_reports.state_count("Connecticut") %>
    }, {
      "id": "US-DE",
      "value": <%= @big_foot_reports.state_count("Delaware") %>
    }, {
      "id": "US-FL",
      "value": <%= @big_foot_reports.state_count("Florida") %>
    }, {
      "id": "US-GA",
      "value": <%= @big_foot_reports.state_count("Georgia") %>
    }, {
      "id": "US-HI",
      "value": <%= @big_foot_reports.state_count("Hawaii") %>
    }, {
      "id": "US-ID",
      "value": <%= @big_foot_reports.state_count("Idaho") %>
    }, {
      "id": "US-IL",
      "value": <%= @big_foot_reports.state_count("Illinois") %>
    }, {
      "id": "US-IN",
      "value": <%= @big_foot_reports.state_count("Indiana") %>
    }, {
      "id": "US-IA",
      "value": <%= @big_foot_reports.state_count("Iowa") %>
    }, {
      "id": "US-KS",
      "value": <%= @big_foot_reports.state_count("Kansas") %>
    }, {
      "id": "US-KY",
      "value": <%= @big_foot_reports.state_count("Kentukcy") %>
    }, {
      "id": "US-LA",
      "value": <%= @big_foot_reports.state_count("Louisiana") %>
    }, {
      "id": "US-ME",
      "value": <%= @big_foot_reports.state_count("Maine") %>
    }, {
      "id": "US-MD",
      "value": <%= @big_foot_reports.state_count("Maryland") %>
    }, {
      "id": "US-MA",
      "value": <%= @big_foot_reports.state_count("Massachusetts") %>
    }, {
      "id": "US-MI",
      "value": <%= @big_foot_reports.state_count("Michigan") %>
    }, {
      "id": "US-MN",
      "value": <%= @big_foot_reports.state_count("Minnesota") %>
    }, {
      "id": "US-MS",
      "value": <%= @big_foot_reports.state_count("Mississippi") %>
    }, {
      "id": "US-MO",
      "value": <%= @big_foot_reports.state_count("Missouri") %>
    }, {
      "id": "US-MT",
      "value": <%= @big_foot_reports.state_count("Montana") %>
    }, {
      "id": "US-NE",
      "value": <%= @big_foot_reports.state_count("Nebraska") %>
    }, {
      "id": "US-NV",
      "value": <%= @big_foot_reports.state_count("Nevada") %>
    }, {
      "id": "US-NH",
      "value": <%= @big_foot_reports.state_count("New Hampshire") %>
    }, {
      "id": "US-NJ",
      "value": <%= @big_foot_reports.state_count("New Jersey") %>
    }, {
      "id": "US-NM",
      "value": <%= @big_foot_reports.state_count("New Mexico") %>
    }, {
      "id": "US-NY",
      "value": <%= @big_foot_reports.state_count("New York") %>
    }, {
      "id": "US-NC",
      "value": <%= @big_foot_reports.state_count("North Carolina") %>
    }, {
      "id": "US-ND",
      "value": <%= @big_foot_reports.state_count("North Dakota") %>
    }, {
      "id": "US-OH",
      "value": <%= @big_foot_reports.state_count("Ohio") %>
    }, {
      "id": "US-OK",
      "value": <%= @big_foot_reports.state_count("Oklahoma") %>
    }, {
      "id": "US-OR",
      "value": <%= @big_foot_reports.state_count("Oregon") %>
    }, {
      "id": "US-PA",
      "value": <%= @big_foot_reports.state_count("Pennsylvania") %>
    }, {
      "id": "US-RI",
      "value": <%= @big_foot_reports.state_count("Rhode Island") %>
    }, {
      "id": "US-SC",
      "value": <%= @big_foot_reports.state_count("South Carolina") %>
    }, {
      "id": "US-SD",
      "value": <%= @big_foot_reports.state_count("South Dakota") %>
    }, {
      "id": "US-TN",
      "value": <%= @big_foot_reports.state_count("Tennessee") %>
    }, {
      "id": "US-TX",
      "value": <%= @big_foot_reports.state_count("Texas") %>
    }, {
      "id": "US-UT",
      "value": <%= @big_foot_reports.state_count("Utah") %>
    }, {
      "id": "US-VT",
      "value": <%= @big_foot_reports.state_count("Vermont") %>
    }, {
      "id": "US-VA",
      "value": <%= @big_foot_reports.state_count("Virginia") %>
    }, {
      "id": "US-WA",
      "value": <%= @big_foot_reports.state_count("Washington") %>
    }, {
      "id": "US-WV",
      "value": <%= @big_foot_reports.state_count("West Virginia") %>
    }, {
      "id": "US-WI",
      "value": <%= @big_foot_reports.state_count("Wisconsin") %>
    }, {
      "id": "US-WY",
      "value": <%= @big_foot_reports.state_count("Wyoming") %>
    } ]
  },

  "areasSettings": {
    "autoZoom": true
  },

  "valueLegend": {
    "right": 10,
    "minValue": "low",
    "maxValue": "high"
  },

  "export": {
    "enabled": true
  }

} );
</script>

<!-- HTML -->
<div id="chartdiv"></div>

app/views/welcome/index.html.erb
<% if current_user %>
  <h3>Welcome, <%= "#{current_user.first_name} #{current_user.last_name}" %></h3>
<% end %>

<div class="pictures">
  <img src="https://uproxx.files.wordpress.com/2016/04/trailer-park-boys-bubbles-1.jpg?quality=100&w=650" alt="Bubbles">
  <img src="http://mauiwatch.com/wp-content/uploads/2017/04/Harry-1.jpg" alt="Harry">
</div>